"""TTS runtime package (aligned with TS src/tts/ and speech-core)."""

from openclaw.tts.tts import (
    get_tts_max_length,
    get_tts_persona,
    get_tts_provider,
    is_summarization_enabled,
    is_tts_enabled,
    is_tts_provider_configured,
    list_tts_personas,
    maybe_apply_tts_to_payload,
    normalize_tts_auto_mode,
    resolve_explicit_tts_overrides,
    resolve_tts_auto_mode,
    resolve_tts_config,
    resolve_tts_prefs_path,
    resolve_tts_provider_order,
    set_summarization_enabled,
    set_tts_enabled,
    set_tts_max_length,
    set_tts_persona,
    set_tts_provider,
    synthesize_speech,
    text_to_speech,
    text_to_speech_telephony,
)

__all__ = [
    "get_tts_max_length",
    "get_tts_persona",
    "get_tts_provider",
    "is_summarization_enabled",
    "is_tts_enabled",
    "is_tts_provider_configured",
    "list_tts_personas",
    "maybe_apply_tts_to_payload",
    "normalize_tts_auto_mode",
    "resolve_explicit_tts_overrides",
    "resolve_tts_auto_mode",
    "resolve_tts_config",
    "resolve_tts_prefs_path",
    "resolve_tts_provider_order",
    "set_summarization_enabled",
    "set_tts_enabled",
    "set_tts_max_length",
    "set_tts_persona",
    "set_tts_provider",
    "synthesize_speech",
    "text_to_speech",
    "text_to_speech_telephony",
]
